site_name: Keystone Vertex Docs
site_description: Keystone Vertex Solana program suite documentation
site_url: https://keystone-labs.github.io/vertex
repo_url: https://github.com/keystone-labs/vertex
nav:
  - Overview: docs/index.md
  - Programs:
      - Launchpad: docs/programs/launchpad.md
      - AMM: docs/programs/amm.md
      - Staking: docs/programs/staking.md
      - Vesting: docs/programs/vesting.md
  - Operations:
      - Deployments: docs/operations/deployments.md
      - Monitoring: docs/operations/monitoring.md
  - Security: docs/security.md
  - CLI: docs/cli.md
  - SDK: docs/sdk.md
  - FAQ: docs/faq.md
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: teal
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
